version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: taskflow
    restart: always
    ports:
      - "54421:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow
    volumes:
    - taskflow_data:/var/lib/postgresql/taskflow_data

volumes:
  taskflow_data:
